# Generated by Django 4.2.5 on 2023-10-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('referencePrice', models.FloatField()),
                ('openPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('avgPrice', models.FloatField()),
                ('lastSize', models.IntegerField()),
            ],
            options={
                'db_table': 'quote',
            },
        ),
    ]
